version: '3.6'
services:
  timescaledb:
    container_name: timescaledb
    image: samagragovernance/postgres:latest-pg15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: postgrespassword